export const enum OauthActionTypes {
  SET_TO_LOGGING = 'OAUTH_LOGGING',
  SET_TO_LOGIN_FAILED = 'OAUTH_LOGIN_FAILED',
  SET_TOKEN = 'OAUTH_SET_TOKEN',
  REMOVE_TOKEN = 'OAUTH_REMOVE_TOKEN',
  SET_QUYEN = 'OAUTH_SET_QUYEN'
}
