export const enum tcTreedActionTypes {
  SET_TC_TREE = 'TC_TREE_SET',
  SET_TC_LOGOUT = 'TC_LOGOUT_SET',
  SET_TC_REFRESH = 'TC_REFRESH_SET',
  SET_TC_KEY = 'TC_KEY_SET',
  SET_TC_SELECTED = 'TC_SELECTED_SET',
}
