//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SMART.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Role()
        {
            this.Sys_Role_Module_Function = new HashSet<Sys_Role_Module_Function>();
        }
    
        public System.Guid RoleId { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid OrganizationId { get; set; }
        public string RoleCode { get; set; }
        public string RoleName { get; set; }
        public int Collocation { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.Guid CreateUser { get; set; }
        public System.Guid UpdateUser { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Sys_Company Sys_Company { get; set; }
        public virtual Sys_Organization Sys_Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Role_Module_Function> Sys_Role_Module_Function { get; set; }
    }
}
