//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SMART.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Role_Module_Function
    {
        public System.Guid RoleId { get; set; }
        public System.Guid ModuleId { get; set; }
        public Nullable<System.Guid> FunctionId { get; set; }
    
        public virtual Sys_Function Sys_Function { get; set; }
        public virtual Sys_Module Sys_Module { get; set; }
        public virtual Sys_Role Sys_Role { get; set; }
    }
}
