export class PERMSConstant {
    public static DM = {
        HINHTHUCKYLUAT_CAPNHAT: 'DM-HINHTHUCKYLUAT_CAPNHAT',
        TRINHDODAOTAO_XOA: 'DM-TRINHDODAOTAO_XOA',
        KHOIDONVI_CAPNHAT: 'DM-KHOIDONVI_CAPNHAT',
        NGHENGHIEPTP_XOA: 'DM-NGHENGHIEPTP_XOA',
        TONGIAO_XOA: 'DM-TONGIAO_XOA',
        DANTOC_CAPNHAT: 'DM-DANTOC_CAPNHAT',
        TONGIAO_CAPNHAT: 'DM-TONGIAO_CAPNHAT',
        KHOIDONVI_XOA: 'DM-KHOIDONVI_XOA',
        LINHVUCDAOTAO_CAPNHAT: 'DM-LINHVUCDAOTAO_CAPNHAT',
        CHUYENNGANHDAOTAO_XOA: 'DM-CHUYENNGANHDAOTAO_XOA',
        CHUCVU_XOA: 'DM-CHUCVU_XOA',
        CHUYENNGANHDAOTAO_CAPNHAT: 'DM-CHUYENNGANHDAOTAO_CAPNHAT',
        HINHTHUCKHENTHUONG_CAPNHAT: 'DM-HINHTHUCKHENTHUONG_CAPNHAT',
        DANTOC_XOA: 'DM-DANTOC_XOA',
        TRINHDODAOTAO_CAPNHAT: 'DM-TRINHDODAOTAO_CAPNHAT',
        HINHTHUCKHENTHUONG_XOA: 'DM-HINHTHUCKHENTHUONG_XOA',
        HINHTHUCKYLUAT_XOA: 'DM-HINHTHUCKYLUAT_XOA',
        LINHVUCDAOTAO_XOA: 'DM-LINHVUCDAOTAO_XOA',
        DIABAN_XOA: 'DM-DIABAN_XOA',
        NGHENGHIEPTP_CAPNHAT: 'DM-NGHENGHIEPTP_CAPNHAT',
        CHUCVU_CAPNHAT: 'DM-CHUCVU_CAPNHAT',
        CHUONGTRINH_CAPNHAT: 'DM-CHUONGTRINH_CAPNHAT',
        CHUONGTRINH_XOA: 'DM-CHUONGTRINH_XOA',
        DIABAN_CAPNHAT: 'DM-DIABAN_CAPNHAT',
        QUANLYDANHSACHCANBO_CAPNHAT: 'DM-QUANLYDANHSACHCANBO_CAPNHAT',
        QUANLYDANHSACHCANBO_XOA: 'DM-QUANLYDANHSACHCANBO_XOA',
        LOAICHUCVU_CAPNHAT: 'DM-LOAICHUCVU_CAPNHAT',
        LOAICHUCVU_XOA: 'DM-LOAICHUCVU_XOA',
        QUANLYDANHMUCHOIVIEN_CAPNHAT: 'DM-QUANLYDANHMUCHOIVIEN_CAPNHAT',
        QUANLYDANHMUCHOIVIEN_XOA: 'DM-QUANLYDANHMUCHOIVIEN_XOA',
        QUANLYTHONGTINDANHGIACANBO_CAPNHAT: 'DM-QLTTDANHGIACANBO_CAPNHAT',
        QUANLYTHONGTINDANHGIACANBO_XOA: 'DM-QLTTDANHGIACANBO_XOA',
        QUANLYDANHSACHLANHDAODONVI_CAPNHAT: 'DM-QLDSLANHDAODONVI_CAPNHAT',
        QUANLYDANHSACHLANHDAODONVI_XOA: 'DM-QLDSLANHDAODONVI_XOA',
        TINHTRANGHV_CAPNHAT: 'DM-TINHTRANGHV_CAPNHAT',
        TINHTRANGHV_XOA: 'DM-TINHTRANGHV_XOA',
        LOAIVB_CAPNHAT: 'DM_LOAIVB_CAPNHAT',
        LOAIVB_XOA: 'DM_LOAIVB_XOA',
        BONGANH_CAPNHAT: 'DM-BONGANH_CAPNHAT',
        BONGANH_XOA: 'DM-BONGANH_XOA',
        DOITUONGKHENTHUONG_CAPNHAT: 'DM-DOITUONGKHENTHUONG_CAPNHAT',
        DOITUONGKHENTHUONG_XOA: 'DM-DOITUONGKHENTHUONG_XOA',

        QUANLYKHUVUC_CAPNHAT: 'DM-QUANLYKHUVUC_CAPNHAT',
        QUANLYKHUVUC_XOA: 'DM-QUANLYKHUVUC_XOA',
    };
    public static HV = {
        SOLUONGPHUNU_XOA: 'HV-SOLUONGPHUNU_XOA',
        DONVIDACTHU_XOA: 'HV-DONVIDACTHU_XOA',
        DONVIDACTHU_CAPNHAT: 'HV-DONVIDACTHU_CAPNHAT',
        BIENDONG_CAPNHAT: 'HV-BIENDONG_CAPNHAT',
        THAMGIAHOATDONG_CAPNHAT: 'HV-THAMGIAHOATDONG_CAPNHAT',
        THONGTINKHAC_XOA: 'HV-THONGTINKHAC_XOA',
        HOSOHOIVIEN_XOA: 'HV-HOSOHOIVIEN_XOA',
        // DANHGIAXEPLOAI_XOA: 'HV-DANHGIAXEPLOAI_XOA',
        QUATRINHKHENTHUONG_XOA: 'HV-QUATRINHKHENTHUONG_XOA',
        SOLUONGPHUNU_CAPNHAT: 'HV-SOLUONGPHUNU_CAPNHAT',
        TONGHOPTOCHUCHOIVIEN_CAPNHAT: 'HV-TONGHOPTOCHUCHOIVIEN_CAPNHAT',
        // DANHGIAXEPLOAI_CAPNHAT: 'HV-DANHGIAXEPLOAI_CAPNHAT',
        THONGTINKHAC_CAPNHAT: 'HV-THONGTINKHAC_CAPNHAT',
        QUATRINHTHAMGIAHOI_CAPNHAT: 'HV-QUATRINHTHAMGIAHOI_CAPNHAT',
        CHUCVUHOI_CAPNHAT: 'HV-CHUCVUHOI_CAPNHAT',
        QUATRINHKHENTHUONG_CAPNHAT: 'HV-QUATRINHKHENTHUONG_CAPNHAT',
        THAMGIAHOATDONG_XOA: 'HV-THAMGIAHOATDONG_XOA',
        HOSOHOIVIEN_CAPNHAT: 'HV-HOSOHOIVIEN_CAPNHAT',
        TINHTRANGCHINHTRI_CAPNHAT: 'HV-TINHTRANGCHINHTRI_CAPNHAT',
        THANHVIENCAULACBO_CAPNHAT: 'HV-THANHVIENCAULACBO_CAPNHAT',
        THANHVIENCAULACBO_XOA: 'HV-THANHVIENCAULACBO_XOA',
        QUATRINHKHENTHUONG_CLB_UPDATE: 'HV-QUATRINHKHENTHUONG-CLB_UPDATE',
        QUATRINHKHENTHUONG_CLB_XOA: 'HV-QUATRINHKHENTHUONG-CLB_XOA',
        THONGTINKHAC_CLB_CAPNHAT: 'HV-THONGTINKHAC-CLB_CAPNHAT',
        THONGTINKHAC_CLB_XOA: 'HV-THONGTINKHAC-CLB_XOA',
        TINHTRANGCHINHTRI_CLB_CAPNHAT: 'HV-TINHTRANGCHINHTRI-CLB_CAPNHAT',
        CHUCVUHOI_CLB_CAPNHAT: 'HV-CHUCVUHOI-CLB_CAPNHAT',
        QUATRINHTHAMGIAHOI_CLB_CAPNHAT: 'HV-QUATRINHTHAMGIAHOI-CLB_UPDATE',
        BAOCAOHOIVIENKHENTHUONG_CAPNHAT: 'HV-BCHOIVIENKHENTHUONG_CAPNHAT',
        BAOCAOHOIVIENLADANGVIEN_CAPNHAT: 'HV-BCHOIVIENLADANGVIEN_CAPNHAT',
        BIENDONG_CLB_CAPNHAT: 'HV-BIENDONG_CLB_CAPNHAT',
        CAULACBO_CAPNHAT: 'HV-CAULACBO_CAPNHAT',
        CHITO_CAPNHAT: 'HV-CHITO_CAPNHAT',
        DBHC_EXCEL: 'HV-DBHC-EXCEL',
        HDH_EXCEL: 'HV-HDH-EXCEL',
        HOIPHI_XOA: 'HV-HOIPHI_XOA',
        HOIPHI_CAPNHAT: 'HV-HOIPHI_CAPNHAT'
    };
    public static QTHT = {
        VAITRO_CAPNHAT: 'QTHT-VAITRO_CAPNHAT',
        MODULE_XOA: 'QTHT-MODULE_XOA',
        NHOM_CAPNHAT: 'QTHT-NHOM_CAPNHAT',
        DIEUHUONG_XOA: 'QTHT-DIEUHUONG_XOA',
        NGUOIDUNG_CAPNHAT: 'QTHT-NGUOIDUNG_CAPNHAT',
        LOAIMODULE_CAPNHAT: 'QTHT-LOAIMODULE_CAPNHAT',
        MODULE_CAPNHAT: 'QTHT-MODULE_CAPNHAT',
        VAITRO_XOA: 'QTHT-VAITRO_XOA',
        NHOM_XOA: 'QTHT-NHOM_XOA',
        CHUCNANG_CAPNHAT: 'QTHT-CHUCNANG_CAPNHAT',
        LOAIMODULE_XOA: 'QTHT-LOAIMODULE_XOA',
        CHUCNANG_XOA: 'QTHT-CHUCNANG_XOA',
        DIEUHUONG_CAPNHAT: 'QTHT-DIEUHUONG_CAPNHAT',
        NGUOIDUNG_XOA: 'QTHT-NGUOIDUNG_XOA',
        SUKIEN_CAPNHAT: 'QTHT-SUKIEN_CAPNHAT',
        SUKIEN_XOA: 'QTHT-SUKIEN_XOA',
        CAUHINHHETHONG_CAPNHAT: 'QTHT-CAUHINHHETHONG_CAPNHAT',
        CAUHINHHETHONG_XOA: 'QTHT-CAUHINHHETHONG_XOA',
        KYBAOCAO_CAPNHAT: 'QTHT-KYBAOCAO_CAPNHAT',
        KYBAOCAO_XOA: 'QTHT-KYBAOCAO_XOA',
    };
    public static TC = {
        PHONGBAN_XOA: 'TC-PHONGBAN_XOA',
        PHONGBAN_CAPNHAT: 'TC-PHONGBAN_CAPNHAT',

        COCAUTOCHUC_XOA: 'TC-COCAUTOCHUC_XOA',
        COCAUTOCHUC_CAPNHAT: 'TC-COCAUTOCHUC_CAPNHAT',
        COCAUTOCHUC_CAPNHAT_18T: 'TC-COCAUTOCHUC_CAPNHAT_18T',

        PHANLOAITOCHUC_CAPNHAT: 'TC-PHANLOAITOCHUC_CAPNHAT',
        PHANLOAITOCHUC_XOA: 'TC-PHANLOAITOCHUC_XOA',

        CAULACBO_CAPNHAT: 'TC-CAULACBO_CAPNHAT',
        CAULACBO_XOA: 'TC-CAULACBO_XOA',

        LOAIHINHCLB_CAPNHAT: 'TC-LOAIHINHCLB_CAPNHAT',
        LOAIHINHCLB_XOA: 'TC-LOAIHINHCLB_XOA',
        // bangnc
        DANHGIAXEPLOAI_XOA: 'TC-DANHGIAXEPLOAI_XOA',
        DANHGIAXEPLOAI_CAPNHAT: 'TC-DANHGIAXEPLOAI_CAPNHAT',

        CUMTHIDUA_CAPNHAT: 'TC-CUMTHIDUA_CAPNHAT',
        CUMTHIDUA_CAPNHAT_TRUONGCUM: 'TC-CUMTHIDUA_CAPNHAT_TRUONGCUM',
        CUMTHIDUA_XOA: 'TC-CUMTHIDUA_XOA',
    };
    public static VB = {
        LOAIVANBAN_XOA: 'VB-LOAIVANBAN_XOA',
        LOAIVANBAN_CAPNHAT: 'VB-LOAIVANBAN_CAPNHAT',
        VANBANBIEUMAU_XOA: 'VB-VANBANBIEUMAU_XOA',
        VANBANBIEUMAU_CAPNHAT: 'VB-VANBANBIEUMAU_CAPNHAT'
    };
    public static CB = {
        HOSOCANBO_XOA: 'CB-HOSOCANBO_XOA',
        HOSOCANBO_CAPNHAT: 'CB-HOSOCANBO_CAPNHAT',
        KHOIDACTHU_XOA: 'CB-KHOIDACTHU_XOA',
        KHOIDACTHU_CAPNHAT: 'CB-KHOIDACTHU_CAPNHAT',

        QUATRINHCONGTAC_SHOW: 'CB-QUATRINHCONGTAC_SHOW',
        QUATRINHCONGTAC_CAPNHAT: 'CB-QUATRINHCONGTAC_CAPNHAT',
        QUATRINHCONGTAC_XOA: 'CB-QUATRINHCONGTAC_XOA',

        THAMGIAHOATDONG_SHOW: 'CB-THAMGIAHOATDONG_SHOW',
        THAMGIAHOATDONG_CAPNHAT: 'CB-THAMGIAHOATDONG_CAPNHAT',
        THAMGIAHOATDONG_XOA: 'CB-THAMGIAHOATDONG_XOA',

        QUATRINHDAOTAO_SHOW: 'CB-QUATRINHDAOTAO_SHOW',
        QUATRINHDAOTAO_CAPNHAT: 'CB-QUATRINHDAOTAO_CAPNHAT',
        QUATRINHDAOTAO_XOA: 'CB-QUATRINHDAOTAO_XOA',

        THONGTINKHAC_SHOW: 'CB-THONGTINKHAC_SHOW',
        THONGTINKHAC_CAPNHAT: 'CB-THONGTINKHAC_CAPNHAT',
        THONGTINKHAC_XOA: 'CB-THONGTINKHAC_XOA',

        BONHIEM_SHOW: 'CB-BONHIEM_SHOW',
        BONHIEM_CAPNHAT: 'CB-BONHIEM_CAPNHAT',
        BONHIEM_XOA: 'CB-BONHIEM_XOA',

        DIEUDONG_SHOW: 'CB-DIEUDONG_SHOW',
        DIEUDONG_CAPNHAT: 'CB-DIEUDONG_CAPNHAT',
        DIEUDONG_XOA: 'CB-DIEUDONG_XOA',

        NGHIHUU_SHOW: 'CB-NGHIHUU_SHOW',
        NGHIHUU_CAPNHAT: 'CB-NGHIHUU_CAPNHAT',
        NGHIHUU_XOA: 'CB-NGHIHUU_XOA',

        CHUCVU_CAPNHAT: 'CB-CHUCVU_CAPNHAT',
        BCHDANGBOCANBO_CAPNHAT: 'CB-BCHDANGBOCANBO_CAPNHAT',
        QUOCHOIHDNDCANBO_CAPNHAT: 'CB-QUOCHOIHDNDCANBO_CAPNHAT',
        QUATRINHKHENTHUONG_XOA: 'CB-QUATRINHKHENTHUONG_XOA',
        QUATRINHKHENTHUONG_CAPNHAT: 'CB-QUATRINHKHENTHUONG_CAPNHAT',

        QUATRINHKYLUAT_SHOW: 'CB-QUATRINHKYLUAT_SHOW',
        QUATRINHKYLUAT_XOA: 'CB-QUATRINHKYLUAT_XOA',
        QUATRINHKYLUAT_CAPNHAT: 'CB-QUATRINHKYLUAT_CAPNHAT',

        QUATRINHKHENTHUONG_SHOW: 'CB-KHENTHUONG_SHOW',

        CHIHOITRUONG_CAPNHAT: 'CB-CHIHOITRUONG_CAPNHAT',
        CB_EXCEL: 'CB-EXCEL',

        MANHINHCHITIET_TAPHUAN_SHOW: 'CB-MANHINHCHITIET_TAPHUAN_SHOW',
        MANHINHCHITIET_DIEUDONG_SHOW: 'CB-MANHINHCHITIET_DIEUDONG_SHOW',
        MANHINHCHITIET_CONGTAC_SHOW: 'CB-MANHINHCHITIET_CONGTAC_SHOW',
    };
    public static CBN = {
        HOSOCANBONU_XOA: 'CBN-HOSOCANBONU_XOA',
        HOSOCANBONU_CAPNHAT: 'CBN-HOSOCANBONU_CAPNHAT',
        HOSOCANBONU_EXCEL: 'CBN-HOSOCANBONU_EXCEL',
        // không dùng
        THAYDOICHUCVU_XOA: 'CBN-THAYDOICHUCVU_XOA',
        THAYDOICHUCVU_CAPNHAT: 'CBN-THAYDOICHUCVU_CAPNHAT',
        CHUCVUHOI_CAPNHAT: 'CBN-CHUCVUHOI_CAPNHAT',
        THONGTINKHAC_XOA: 'CBN-THONGTINKHAC_XOA',
        THONGTINKHAC_CAPNHAT: 'CBN-THONGTINKHAC_CAPNHAT',
           // end không dùng
        TONGSOLANHDAO_XOA: 'CBN-TONGSOLANHDAO_XOA',
        TONGSOLANHDAO_CAPNHAT: 'CBN-TONGSOLANHDAO_CAPNHAT',

        HINHTHUCKYLUATCBN_XOA: 'CBN-HINHTHUCKYLUAT_XOA',
        HINHTHUCKYLUATCBN_CAPNHAT: 'CBN-HINHTHUCKYLUAT_CAPNHAT',

        DIEUDONG_SHOW: 'CBN-DIEUDONG_SHOW',
        DIEUDONG_CAPNHAT: 'CBN-DIEUDONG_CAPNHAT',
        DIEUDONG_XOA: 'CBN-DIEUDONG_XOA',

        THAMGIAHD_SHOW: 'CBN-THAMGIAHD_SHOW',
        THAMGIAHD_CAPNHAT: 'CBN-THAMGIAHD_CAPNHAT',
        THAMGIAHD_XOA: 'CBN-THAMGIAHD_XOA',
    };
    public static TDKT = {
        CHITIEU_XOA: 'TDKT-CHITIEU_XOA',
        CHITIEU_CAPNHAT: 'TDKT-CHITIEU_CAPNHAT',
        BOCHITIEUTW_XOA: 'TDKT-BOCHITIEUTW_XOA',
        BOCHITIEUTW_CAPNHAT: 'TDKT-BOCHITIEUTW_CAPNHAT',
        KEHOACHTRIENKHAI_XOA: 'TDKT-KEHOACHTRIENKHAI_XOA',
        KEHOACHTRIENKHAI_CAPNHAT: 'TDKT-KEHOACHTRIENKHAI_CAPNHAT',
        HIEPYKHENTHUONG_XOA: 'TDKT-HIEPYKHENTHUONG_XOA',
        HIEPYKHENTHUONG_CAPNHAT: 'TDKT-HIEPYKHENTHUONG_CAPNHAT',
        DEXUATKHENTHUONG_XOA: 'TDKT-DEXUATKHENTHUONG_XOA',
        DEXUATKHENTHUONG_CAPNHAT: 'TDKT-DEXUATKHENTHUONG_CAPNHAT',
        DEXUATKHENTHUONG_DUYET: 'TDKT-DEXUATKHENTHUONG_DUYET',
        DEXUATKHENTHUONGBCM_CAPNHAT: 'TDKT-DEXUATKHENTHUONGBCM_CAPNHAT',
        DEXUATKHENTHUONGPTDKT_CAPNHAT: 'TDKT-DXKTPTDKT_CAPNHAT',
        TINHOATDONG_XOA: 'TDKT-TINHOATDONG_XOA',
        TINHOATDONG_CAPNHAT: 'TDKT-TINHOATDONG_CAPNHAT',
        QUYETDINHKHENTHUONG_XOA: 'TDKT-QUYETDINHKHENTHUONG_XOA',
        QUYETDINHKHENTHUONG_CAPNHAT: 'TDKT-QUYETDINHKHENTHUONG_CAPNHAT',
        BANDANGKYCHITIEU_XOA: 'TDKT-BANDANGKYCHITIEU_XOA',
        BANDANGKYCHITIEU_CAPNHAT: 'TDKT-BANDANGKYCHITIEU_CAPNHAT',
        BANCHITIEUDANHGIATW_XOA: 'TDKT-BANCHITIEUDANHGIATW_XOA',
        BANCHITIEUDANHGIATW_CAPNHAT: 'TDKT-BANCHITIEUDANHGIATW_CAPNHAT',
        KETQUATHUCHIEN_XOA: 'TDKT-KETQUATHUCHIEN_XOA',
        KETQUATHUCHIEN_CAPNHAT: 'TDKT-KETQUATHUCHIEN_CAPNHAT',
        // CUMTHIDUA_CAPNHAT: 'TDKT-CUMTHIDUA_CAPNHAT',
        //  CUMTHIDUA_XOA: 'TDKT-CUMTHIDUA_XOA',
        QUANLYDOANCONGTAC_CAPNHAT: 'TDKT-QUANLYDOANCONGTAC_CAPNHAT',
        QUANLYDOANCONGTAC_XOA: 'TDKT-QUANLYDOANCONGTAC_XOA',
        KETQUATUDANHGIACHAMDIEM_XOA: 'TDKT-KQTUDANHGIACHAMDIEM_XOA',
        KETQUATUDANHGIACHAMDIEM_CAPNHAT: 'TDKT-KQTUDANHGIACHAMDIEM_CAPNHAT',
        KETQUACHAMDIEMCUABAN_XOA: 'TDKT-KQCHAMDIEMCUABAN_XOA',
        KETQUACHAMDIEMCUABAN_CAPNHAT: 'TDKT-KQCHAMDIEMCUABAN_CAPNHAT',
        KETQUACHAMDIEMCUACUM_XOA: 'TDKT-KQCHAMDIEMCUACUM_XOA',
        KETQUACHAMDIEMCUACUM_CAPNHAT: 'TDKT-KQCHAMDIEMCUACUM_CAPNHAT',

        KETQUACHAMDIEMCUAHDTD_XOA: 'TDKT-KQCHAMDIEMCUAHDTD_XOA',
        KETQUACHAMDIEMCUAHDTD_CAPNHAT: 'TDKT-KQCHAMDIEMCUAHDTD_CAPNHAT',
        BANPHUTRACH_CAPNHAT: 'TDKT-BANPHUTRACH_CAPNHAT',

        XINYKIEN_CAPNHAT: 'TDKT-XINYKIEN_CAPNHAT',
        XINYKIEN_XOA: 'TDKT-XINYKIEN_XOA',

        SUYTONDOANCONGTAC_XOA: 'TDKT-SUYTONDOANCONGTAC_XOA',
        SUYTONDOANCONGTAC_CAPNHAT: 'TDKT-SUYTONDOANCONGTAC_CAPNHAT',
        KHENCAO_CAPNHAT: 'TDKT-KHENCAO_CAPNHAT',
        KHENCAO_XOA: 'TDKT-KHENCAO_XOA',
        DIENHINHCANHAN_CAPNHAT: 'TDKT-DIENHINHCANHAN_CAPNHAT',
        DIENHINHCANHAN_XOA: 'TDKT-DIENHINHCANHAN_XOA',
        MOHINH_CAPNHAT: 'TDKT-MOHINH_CAPNHAT',
        MOHINH_XOA: 'TDKT-MOHINH_XOA',
        MOHINHDIENHINH_CAPNHAT: 'TDKT-MOHINHDIENHINH_CAPNHAT',
        MOHINHDIENHINH_XOA: 'TDKT-MOHINHDIENHINH_XOA',
    };
    public static CLB = {
        HOSO_CAPNHAT: 'CLB-HOSO_CAPNHAT',
        HOSO_XOA: 'CLB-HOSO_XOA',
    };
}

/*
export class LOAICHUCVUConstant {
    public static ChucVuTrongBCHHoi: '001';
    public static ChucVu = {
        ChucVuTrongBCHHoi: '001',
        ChuTichHoiLienHiepPhuNu: '001_CTHLHPN',
        UyVienBanChapHanh: '001_UVBCH'
    };
}
*/
